name: Generate and Upload PDF

on:
  push:


jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can change the Node.js version as needed

      - name: Install Dependencies
        run: npm install markdown-pdf -g

      - name: Generate Markdown File
        run: |
          find . -type f -name "*.md" -exec cat {} + > manual.md.fin
          mv manual.md.fin manual.md

      - name: Generate PDF
        run: |
          markdown-pdf manual.md

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: manual
          path: manual.pdf
