name: Generate Markdown File

on:
  push:
    branches:
      - evo

jobs:
  generate-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install marked --save

      - name: Generate Markdown File
        run: |
          find . -type f -name "*.md" -exec cat {} + > all_md_files.final

      - name: Upload Generated Markdown File
        uses: actions/upload-artifact@v2
        with:
          name: all_md_files
          path: all_md_files.md
