name: Generate PDF from SUMMARY.md and Upload

on:
  push:
    branches:
      - evo  # Specify the branch where SUMMARY.md is located

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4
        # Install Pandoc
        sudo apt-get update
        sudo apt-get install -y pandoc
        # Install pdflatex
        sudo apt-get install -y texlive-xetex
      working-directory: ${{ github.workspace }}

    - name: Generate PDF
      run: |
        # Directory to store downloaded files
        DOWNLOAD_DIR="downloaded_files"
        mkdir -p "$DOWNLOAD_DIR"
        
        # Function to process links in SUMMARY.md
        process_links() {
            local content="$1"
            while IFS= read -r -d $'\n' link; do
                if [[ "$link" =~ ^\[[^\]]+\]:\ (.+)$ ]]; then
                    link_url="${BASH_REMATCH[1]}"
                    if [[ "$link_url" != http* ]]; then
                        # Replace the link in the SUMMARY.md with the local file path
                        content="${content//[$link]: $link_url/[$link]: $link_url}"
                    fi
                fi
            done < <(echo -e "$content")
            echo "$content"
        }
        
        # Process links in SUMMARY.md
        SUMMARY_MD_CONTENT="$(cat SUMMARY.md)"
        SUMMARY_MD_CONTENT=$(process_links "$SUMMARY_MD_CONTENT")
        
        # Save the modified SUMMARY.md
        echo -e "$SUMMARY_MD_CONTENT" > "${DOWNLOAD_DIR}/SUMMARY.md"
        
        # Convert SUMMARY.md to PDF using Pandoc
        pandoc "${DOWNLOAD_DIR}/SUMMARY.md" -o "${DOWNLOAD_DIR}/summary.pdf"
        
        echo "PDF generated: ${DOWNLOAD_DIR}/summary.pdf"
      working-directory: ${{ github.workspace }}

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: summary-pdf
        path: downloaded_files/summary.pdf
