name: Generate and Upload PDF

on:
  push:


jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can change the Node.js version as needed

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-extra texlive-latex-extra texlive-fonts-recommended 

      - name: Generate Markdown File
        run: |
          mkdir ../.gitbook
          cp -Rfv  .gitbook/* ../.gitbook/
          sed -n '/^## Table of Contents$/q;p' manual/mainpage.md >> manual.md.fin
          cat SUMMARY.md >> manual.md.fin
          sed -n '/^## About OpenHD/,$p' manual/mainpage.md >> manual.md.fin
          echo "## About OpenHD" >> manual.md.fin
          cat introduction.md >> manual.md.fin
          cat downloads.md >> manual.md.fin
          echo "#General" >> manual.md.fin
          echo " --------------- " >> manual.md.fin
          echo " --------------- " >> manual.md.fin
          cat general/features.md >> manual.md.fin
          cat general/OpenHD-vs-Alternatives.md >> manual.md.fin
          cat general/troubleshooting.md >> manual.md.fin
          cat general/faq.md >> manual.md.fin
          cat general/software-faq.md >> manual.md.fin
          cat general/contributing.md >> manual.md.fin
          cat general/team.md >> manual.md.fin
          echo "#Installation" >> manual.md.fin
          echo " --------------- " >> manual.md.fin
          echo " --------------- " >> manual.md.fin
          # cat installation-guide.md >> manual.md.fin
          # echo "#Hardware" >> manual.md.fin
          # echo " --------------- " >> manual.md.fin
          # echo " --------------- " >> manual.md.fin
          # cat hardware/first-time-setup.md >> manual.md.fin
          # cat hardware/sbcs.md >> manual.md.fin
          # cat hardware/raspberry.md >> manual.md.fin
          # cat hardware/ochin.md >> manual.md.fin
          # cat hardware/X86.md >> manual.md.fin
          # cat hardware/radxa.md >> manual.md.fin
          # cat hardware/custom-hardware.md >> manual.md.fin
          # cat hardware/discontinued.md >> manual.md.fin
          # cat hardware/jetson.md >> manual.md.fin
          # cat hardware/cameras.md >> manual.md.fin
          # cat hardware/cameras/raspberry-cameras.md >> manual.md.fin
          # cat hardware/cameras/radxa-cameras.md >> manual.md.fin
          # cat hardware/cameras/usb-camera.md >> manual.md.fin
          # cat hardware/cameras/rpi-hdmi-to-csi.md >> manual.md.fin
          # cat hardware/cameras/hdmi-cameras-rpi.md >> manual.md.fin
          # cat hardware/cameras/ip-cameras.md >> manual.md.fin
          # cat hardware/cameras/special-camera.md >> manual.md.fin
          # cat hardware/cameras/custom-unmanaged-camera.md >> manual.md.fin
          # cat hardware/cameras/custom-cameras.md >> manual.md.fin
          # cat hardware/wifi-adapters.md >> manual.md.fin
          # cat hardware/antennas.md >> manual.md.fin
          # cat hardware/flightControllers.md >> manual.md.fin
          # cat hardware/wiring.md >> manual.md.fin
          # cat hardware/displays.md >> manual.md.fin
          # cat hardware/hardware.conf.md >> manual.md.fin
          # echo "## Software Setup" >> manual.md.fin
          # echo " --------------- " >> manual.md.fin
          # echo " --------------- " >> manual.md.fin
          # cat software-setup/inav.md >> manual.md.fin
          # cat software-setup/ardupilot.md >> manual.md.fin
          # cat software-setup/betaflight.md >> manual.md.fin
          # cat software-setup/recording.md >> manual.md.fin
          # cat software-setup/tx-power.md >> manual.md.fin
          # cat software-setup/mcs-via-rc.md >> manual.md.fin
          # cat software-setup/joystick-rc.md >> manual.md.fin
          # cat software-setup/camera-settings.md >> manual.md.fin
          # cat software-setup/tethering.md >> manual.md.fin
          # cat software-setup/ethernet-hotspot.md >> manual.md.fin
          # cat software-setup/wifi-hotspot.md >> manual.md.fin
          # cat software-setup/variable-bitrate.md >> manual.md.fin
          # echo "## Advanced Setup" >> manual.md.fin
          # echo " --------------- " >> manual.md.fin
          # echo " --------------- " >> manual.md.fin
          # cat advanced-setup/air-recording.md >> manual.md.fin
          # cat advanced-setup/dual-camera.md >> manual.md.fin
          # echo "## Ground Station Software" >> manual.md.fin
          # echo " --------------- " >> manual.md.fin
          # echo " --------------- " >> manual.md.fin
          # cat ground-station-software/qopenhd-osd-backup.md >> manual.md.fin
          # cat ground-station-software/qgroundcontrol.md >> manual.md.fin
          # cat ground-station-software/tower.md >> manual.md.fin
          # cat ground-station-software/fpv_vr.md >> manual.md.fin
          # echo "## Developers Corner" >> manual.md.fin
          # echo " --------------- " >> manual.md.fin
          # echo " --------------- " >> manual.md.fin
          # cat developers/porting.md  >> manual.md.fin          
          mv manual.md.fin manual.md

      - name: Generate PDF
        run: |
          pandoc -s manual.md -o manual.pdf

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: manual
          path: manual.pdf
